FROM node:16.16.0-alpine3.16 as builder

WORKDIR /app

COPY . .

RUN yarn install && yarn build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*
COPY --from=builder /app/dist .

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
